spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: tfm

com:
  vanchondo:
    crypto-forecasting:
      url: http://localhost:6060/predict/
    login:
      secretKey: 613f918b1473e1f1faec033e8f5085fa89eee67514a1de963c389919cecbf5ed