
com:
  vanchondo:
    login:
      issuer: tfm-app
      # Minutes
      expirationToken: 1440

      unsecuredUrls:
        - url: /login
          methods: POST
        - url: /register
          methods: POST
        - url: /validate
          methods: GET
        - url: /swagger-ui
          methods: GET