spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

com:
  vanchondo:
    yahoo-finance:
      url: https://query1.finance.yahoo.com/v7/finance/download/
      btc:
        path: BTC-USD
        startDate: 10/15/2014
    login:
      issuer: tfm-app
      # Minutes
      expirationToken: 1440

      unsecuredUrls:
        - url: /login
          methods: POST
        - url: /register
          methods: POST
        - url: /users/available
          methods: GET
        - url: /swagger*
          methods: GET
        - url: /v2/api-docs
          methods: GET